spring.application.name=projeto_hospital_backend

# Conexão com o teu PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=15l12l82r

# Configurações do Hibernate (O tradutor Java -> SQL)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
